name: Resuable child

on:
  workflow_call:                          
    inputs:
      env:                                
        type: string
        description: "Environment variable passed from parent workflow"

jobs:
  reusablejob:
    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Display Environment
        run: echo "Environment is ${{ inputs.env }}"