name: Resuable child

on:
  workflow_call:                          
    inputs:
      env:                                
        type: string
        description: "Environment variable passed from parent workflow"

jobs:
  reusablejob:
    runs-on: windows-latest

    outputs:                     
      resultMessage: ${{ steps.displayEnv.outputs.message }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3


      - name: Display Environment
        run: echo "Environment is ${{ inputs.env }}"

      - id: displayEnv
        run: echo "message=Environment is ${{ inputs.env }}" >> $GITHUB_OUTPUT    

      - name: print output
        run: echo "${{ steps.displayEnv.outputs.message }}"  